-- c02: the anticanonical cone over P^1 x P^1, exactly over QQ.
-- (i) the affine cone C in A^9 over  D = P^1 x P^1  embedded by |O(2,2)|;
-- (ii) C = (three-fold ordinary double point {xy - zw = 0} in A^4) / (+-1);
-- (iii) Zariski tangent space at the vertex has dimension 9, multiplicity 8;
-- (iv) the smoothing  {xy - zw = t}/(+-1)  is smooth of dimension 3 for t = 1.
--
-- (i)
A = QQ[s,t,u,v];
mons = matrix{{s^2*u^2, s^2*u*v, s^2*v^2, s*t*u^2, s*t*u*v, s*t*v^2, t^2*u^2, t^2*u*v, t^2*v^2}};
P8 = QQ[z_0..z_8];
ID = ker map(A, P8, mons);
stderr << "(i)  ideal of D_8 = v_{2,2}(P^1 x P^1) in P^8: codim " << codim ID << ", degree " << degree ID << ", generator degrees " << toString sort flatten degrees source gens ID << endl;
RD = P8/ID;
stderr << "(i)  Hilbert function of the cone ring, n = 0..4: " << toString apply(5, n -> hilbertFunction(n, RD)) << "   (expected (2n+1)^2 = 1,9,25,49,81)" << endl;
-- generated in degree 1: the Hilbert function of the subring generated by degree 1 equals the whole ring by construction (RD is the image of P8).
-- Zariski tangent space at the vertex of the affine cone: 9 minus the number of linear forms in ID.
stderr << "(i)  linear forms in the ideal: " << (#select(flatten entries gens ID, p -> first degree p == 1)) << "   => dim T_0 C = 9" << endl;
stderr << "(i)  multiplicity at the vertex = degree of D_8 = " << degree ID << endl;
--
-- (ii) invariants of the ODP under -1.  Ring of the ODP: Q = QQ[x,y,z,w]/(xy - zw).
--      The 10 quadratic monomials generate the invariants; map a_{ij} -> monomials.
Q4 = QQ[x,y,z,w];
odp = ideal(x*y - z*w);
Sym2 = QQ[a_(0,0),a_(0,1),a_(0,2),a_(0,3),a_(1,1),a_(1,2),a_(1,3),a_(2,2),a_(2,3),a_(3,3)];
vars4 = {x,y,z,w};
quadmons = matrix{ flatten for i from 0 to 3 list for j from i to 3 list vars4#i * vars4#j };
psi = map(Q4/odp, Sym2, quadmons);
Iinv = ker psi;
stderr << "(ii) kernel of  QQ[a_ij] -> QQ[x,y,z,w]/(xy-zw),  a_ij -> (i-th coord)(j-th coord): codim " << codim Iinv << ", degree " << degree Iinv << ", generator degrees " << toString sort flatten degrees source gens Iinv << endl;
lins = select(flatten entries gens Iinv, p -> first degree p == 1);
stderr << "(ii) the unique linear relation: " << toString lins << "   (this is lambda = a_01 - a_23, i.e. xy - zw)" << endl;
stderr << "(ii) after eliminating the linear relation the ideal lives in 9 variables: Hilbert function 0..4 of QQ[a]/Iinv = " << toString apply(5, n -> hilbertFunction(n, Sym2/Iinv)) << endl;
-- the invariant ring is the whole even part: check that every even-degree monomial of Q4 is a polynomial in quadratic monomials (trivially true) and that the map is onto the even part in degrees 2,4,6:
Qodp = Q4/odp;
stderr << "(ii) dimensions of even-degree parts of QQ[x,y,z,w]/(xy-zw): " << toString apply({0,2,4,6,8}, n -> hilbertFunction(n, Qodp)) << "   (must equal 1,9,25,49,81)" << endl;
-- (ii') identify Iinv (after the linear relation) with ID: both are the ideal of the same variety, compare Hilbert functions and check isomorphism by an explicit change of coordinates.
--      Choose coordinates on P(U): D = {q = 0} with q = xy - zw, parametrised by (s,t)x(u,v) -> (x,y,z,w) = (su, tv, sv, tu): indeed (su)(tv) - (sv)(tu) = 0.
par = map(A, Q4, matrix{{s*u, t*v, s*v, t*u}});
imgs = par quadmons;             -- the 10 quadratic monomials evaluated on the parametrisation
stderr << "(ii') the ten quadratic monomials on the parametrisation of {q=0}: " << toString imgs << endl;
Ipar = ker map(A, Sym2, imgs);
stderr << "(ii') ideal of the parametrised image equals Iinv ? " << (Ipar == Iinv) << endl;
--
-- (iii) is contained in (i)-(ii): dim T_0 = 10 - 1 = 9 and multiplicity 8.
--
-- (iv) the smoothing: W_t = {A in Sym^2 U : rank A <= 1, lambda(A) = t}. For t = 1: smooth of dimension 3.
M4 = genericSymmetricMatrix(Sym2, a_(0,0), 4);
Irk1 = minors(2, M4);
lam = a_(0,1) - a_(2,3);
W1 = Irk1 + ideal(lam - 1);
W0 = Irk1 + ideal(lam);
stderr << "(iv) W_0 = cone C: dim " << dim W0 << ", degree " << degree W0 << ", equals Iinv ? " << (W0 == Iinv) << endl;
stderr << "(iv) W_1: dim " << dim W1 << ", degree " << degree W1 << endl;
-- Smoothness of W_1: W_1 is the image of the smooth affine quadric Q_1 = {xy - zw = 1} under u -> u u^T, on which
-- -1 acts freely (0 is not on Q_1), so W_1 is smooth; O(q) acts transitively on Q_1, so one point suffices for the tangent dimension.
-- (The full Jacobian-criterion ideal of W_1 has ~10^7 minors and is not computed.)
Q1 = ideal(x*y - z*w - 1);
stderr << "(iv) Q_1 = {xy - zw = 1}: singular locus = " << toString (Q1 + ideal jacobian Q1) << "  (unit ideal = smooth)" << endl;
-- tangent space of W_1 at one of its points, e.g. A = e_0 e_0^T + ... : take u = (1,1,0,0): u u^T has a_00=a_01=a_11=1, lambda = 1.
pt = {a_(0,0)=>1, a_(0,1)=>1, a_(0,2)=>0, a_(0,3)=>0, a_(1,1)=>1, a_(1,2)=>0, a_(1,3)=>0, a_(2,2)=>0, a_(2,3)=>0, a_(3,3)=>0};
stderr << "(iv) point u u^T with u=(1,1,0,0) lies on W_1 ? " << (sub(gens W1, pt) == 0) << ",  dim of Zariski tangent space there = " << (10 - rank sub(jacobian W1, pt)) << endl;
pt2 = {a_(0,0)=>4, a_(0,1)=>2, a_(0,2)=>2, a_(0,3)=>2, a_(1,1)=>1, a_(1,2)=>1, a_(1,3)=>1, a_(2,2)=>1, a_(2,3)=>1, a_(3,3)=>1};
stderr << "(iv) point u u^T with u=(2,1,1,1) (q(u)=2-1=1) lies on W_1 ? " << (sub(gens W1, pt2) == 0) << ",  dim of Zariski tangent space there = " << (10 - rank sub(jacobian W1, pt2)) << endl;
-- W_0 = the cone: tangent space dimension 9 at the vertex, 3 at a point u u^T with u = (1,0,0,0) on {q = 0}:
pt0 = {a_(0,0)=>1, a_(0,1)=>0, a_(0,2)=>0, a_(0,3)=>0, a_(1,1)=>0, a_(1,2)=>0, a_(1,3)=>0, a_(2,2)=>0, a_(2,3)=>0, a_(3,3)=>0};
stderr << "(iv) W_0 at the vertex: dim T = " << (10 - rank sub(jacobian W0, apply(gens Sym2, v -> v => 0))) << ";  at u u^T, u=(1,0,0,0): on W_0 ? " << (sub(gens W0, pt0) == 0) << ", dim T = " << (10 - rank sub(jacobian W0, pt0)) << endl;
